name: -- reusable -- Check for Changes

on:
  workflow_call:
    outputs:
      should_rebuild:
        description: "Whether containers should be rebuilt"
        value: ${{ jobs.check.outputs.should_rebuild }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_rebuild: ${{ steps.check_changes.outputs.should_rebuild }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5  # Fetch more history for better change detection

      - name: Cache Git history
        uses: actions/cache@v4
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-git-

      - name: Check for changes that require container rebuilds
        id: check_changes
        run: |
          # Check if manual force rebuild is requested
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.force_rebuild }}" == "true" ]]; then
            echo "Force rebuild requested via workflow dispatch"
            echo "should_rebuild=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Check if this is a scheduled run (daily cron)
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Scheduled run, will rebuild containers"
            echo "should_rebuild=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Check for changes in important files
          if git diff --name-only HEAD~1 HEAD | grep -q -E '^Dockerfile$|^scripts/|^\.github/workflows/'; then
            echo "Changes detected in Dockerfile or related files"
            echo "should_rebuild=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes that would require rebuilding containers"
            echo "should_rebuild=false" >> "$GITHUB_OUTPUT"
          fi
