name: 'GitHub Release'
description: 'Create GitHub Release'
inputs:
  version:
    description: 'Version for the release'
    required: true
  should_tag_latest:
    description: 'Whether this version should be tagged as latest'
    required: true
  assets:
    description: 'Assets to include in the release'
    required: false
    default: ''

outputs:
  id:
    description: 'Release ID'
    value: ${{ steps.create_release.outputs.id }}

runs:
  using: 'composite'
  steps:
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        name: "Zabbix Proxy SQLite3 AV - v${{ inputs.version }}"
        body_path: release_notes.md
        draft: false
        prerelease: false
        make_latest: ${{ inputs.should_tag_latest == 'true' }}
        files: ${{ inputs.assets }}
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ github.token }}
