name: 'Docker Build'
description: 'Build and push Docker images'
inputs:
  registry:
    description: 'Registry for the image'
    required: true
  image_name:
    description: 'Image name'
    required: true
  zabbix_version:
    description: 'Zabbix version'
    required: true
  major_minor:
    description: 'Major.minor version'
    required: true
  local_version:
    description: 'Local version with patch increment if needed'
    required: true
  is_local_change:
    description: 'Whether local changes were detected'
    required: true
  is_lts:
    description: 'Whether this is an LTS version'
    required: true
  should_tag_latest:
    description: 'Whether this version should be tagged as latest'
    required: true
  timestamp:
    description: 'Build timestamp'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build and push images
      id: build_push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        provenance: mode=max  # Security: Enable max-level provenance attestation
        sbom: true           # Security: Generate SBOM
        platforms: linux/amd64
        outputs: type=image
        file: ./Dockerfile
        secrets: |
          "github_token=${{ github.token }}"
        build-args: |
          ZABBIX_VERSION=ubuntu-${{ inputs.zabbix_version }}
          BUILD_DATE=${{ inputs.timestamp }}
          VCS_REF=${{ github.sha }}
        # Tags based on version information and status
        # - Local version (which may include .N suffix for local changes)
        # - Major.minor version (only for highest patch version in each series)
        # - Original Zabbix version (if not a local change)
        # - LTS tag if applicable
        # - Latest tag if applicable (only for the absolute highest version)
        tags: |
          ${{
            format(
              '{0}/{1}/{2}:{3}',
              inputs.registry,
              github.repository_owner,
              inputs.image_name,
              inputs.local_version
            )
          }}
          ${{
            format(
              '{0}/{1}/{2}:{3}',
              inputs.registry,
              github.repository_owner,
              inputs.image_name,
              inputs.major_minor
            )
          }}
          ${{
            inputs.is_local_change == 'false' &&
            format(
              '{0}/{1}/{2}:{3}',
              inputs.registry,
              github.repository_owner,
              inputs.image_name,
              inputs.zabbix_version
            ) || ''
          }}
          ${{
            inputs.is_lts == 'true' &&
            format(
              '{0}/{1}/{2}:lts',
              inputs.registry,
              github.repository_owner,
              inputs.image_name
            ) || ''
          }}
          ${{
            inputs.should_tag_latest == 'true' &&
            format(
              '{0}/{1}/{2}:latest',
              inputs.registry,
              github.repository_owner,
              inputs.image_name
            ) || ''
          }}
        # Image metadata labels
        # - Basic metadata
        # - Source control information
        # - Build reproducibility metadata
        # - Legal information
        # - Custom Zabbix metadata
        labels: |
          org.opencontainers.image.title=Zabbix Proxy SQLite3 for AV Systems
          org.opencontainers.image.description=Zabbix Proxy SQLite3 for AV Systems
          org.opencontainers.image.version=${{ inputs.zabbix_version }}
          org.opencontainers.image.base.name=zabbix/zabbix-proxy-sqlite3
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.created=${{ inputs.timestamp }}
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.vendor=${{ github.repository_owner }}
          org.opencontainers.image.licenses=AGPL-3.0
          org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}/blob/main/README.md
          org.zabbix.upstream.version=${{ inputs.zabbix_version }}
          org.zabbix.local.version=${{ inputs.local_version }}
          org.zabbix.build.date=${{ inputs.timestamp }}
          org.zabbix.vcs.ref=${{ github.sha }}
          org.zabbix.container.immutable=true

    - name: Record build attempt status
      if: always()
      shell: bash
      run: |
        echo "## ðŸ—ï¸ Build Attempt Status" >> $GITHUB_STEP_SUMMARY
        echo "| âœ… Status | Build completed |" >> $GITHUB_STEP_SUMMARY
        # Prepare image path for use in reporting
        REGISTRY="${{ inputs.registry }}"
        OWNER="${{ github.repository_owner }}"
        IMG_NAME="${{ inputs.image_name }}"
        VERSION="${{ inputs.local_version }}"
        IMAGE_TAG="$REGISTRY/$OWNER/$IMG_NAME:$VERSION"
        echo "| ðŸ·ï¸ Image Tag | $IMAGE_TAG |" >> $GITHUB_STEP_SUMMARY
        echo "| ðŸ“‹ Zabbix Version | ${{ inputs.zabbix_version }} |" >> $GITHUB_STEP_SUMMARY
