name: 'Generate SLSA Provenance'
description: 'Generates SLSA provenance for a Docker image'
inputs:
  image_name:
    description: 'Full name of the Docker image (repository/image)'
    required: true
  tag:
    description: 'Tag of the Docker image'
    required: true
  registry:
    description: 'Container registry where the image is stored'
    required: true
    default: 'ghcr.io'
  cosign_key:
    description: 'Path to Cosign key or Cosign identity token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.2.0'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate SLSA provenance
      id: slsa
      shell: bash
      run: |
        echo "::group::Generating SLSA provenance"
        IMAGE_REF="${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}"
        echo "Generating provenance for $IMAGE_REF"

        if [ -n "${{ inputs.cosign_key }}" ]; then
          echo "Using provided Cosign key or identity"
          cosign attest --predicate-type slsaprovenance --type slsaprovenance --key "${{ inputs.cosign_key }}" "$IMAGE_REF"
        else
          echo "Using ambient GitHub OIDC identity"
          cosign attest --predicate-type slsaprovenance --type slsaprovenance --yes "$IMAGE_REF"
        fi
        echo "::endgroup::"

        echo "SLSA provenance generated and signed for $IMAGE_REF"
