name: 'Sign Docker Image'
description: 'Signs a Docker image with Cosign'
inputs:
  image_name:
    description: 'Full name of the Docker image (repository/image)'
    required: true
  tags:
    description: 'Tags of the Docker image (comma-separated)'
    required: true
  registry:
    description: 'Container registry where the image is stored'
    required: true
    default: 'ghcr.io'
  cosign_key:
    description: 'Path to Cosign key or Cosign identity token'
    required: false
  identity_token:
    description: 'OIDC identity token for keyless signing'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.2.0'

    - name: Sign Docker image with Cosign
      id: sign_image
      shell: bash
      run: |
        echo "::group::Signing Docker image"
        IFS=',' read -ra TAG_ARRAY <<< "${{ inputs.tags }}"
        for TAG in "${TAG_ARRAY[@]}"; do
          IMAGE_REF="${{ inputs.registry }}/${{ inputs.image_name }}:${TAG}"
          echo "Signing image: $IMAGE_REF"

          if [ -n "${{ inputs.cosign_key }}" ]; then
            echo "Using provided Cosign key"
            cosign sign --key "${{ inputs.cosign_key }}" "$IMAGE_REF"
          else
            echo "Using ambient GitHub OIDC identity"
            cosign sign --yes "$IMAGE_REF"
          fi

          echo "✅ Signed $IMAGE_REF"
        done
        echo "::endgroup::"

        echo "All images signed successfully"
