name: 'Verify Docker Attestations'
description: 'Verifies Docker image attestations (SBOM and Provenance)'
inputs:
  image:
    description: 'Full image reference including tag'
    required: true
outputs:
  sbom_verified:
    description: 'Whether SBOM attestation was verified'
    value: ${{ steps.check_results.outputs.sbom_verified }}
  provenance_verified:
    description: 'Whether Provenance attestation was verified'
    value: ${{ steps.check_results.outputs.provenance_verified }}

runs:
  using: "composite"
  steps:
    - name: Verify Docker Image Attestations
      id: verify_attestations
      shell: bash
      continue-on-error: true
      run: |
        echo "## Docker Image Attestations" >> $GITHUB_STEP_SUMMARY
        IMAGE_REF="${{ inputs.image }}"

        echo "Verifying attestations for image: $IMAGE_REF" >> $GITHUB_STEP_SUMMARY

        # Install Cosign if not already available
        if ! command -v cosign &> /dev/null; then
          echo "Installing Cosign for attestation verification..." >> $GITHUB_STEP_SUMMARY
          COSIGN_VERSION=v2.2.3
          wget -q -O cosign "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
        fi

        # Create output variables with default values
        SBOM_VERIFIED=false
        PROVENANCE_VERIFIED=false

        # Verify SBOM attestation
        echo "### SBOM Attestation" >> $GITHUB_STEP_SUMMARY
        if cosign verify-attestation --type cyclonedx \
           "$IMAGE_REF" \
           --certificate-identity-regexp "https://github.com/docker/build-push-action" \
           --certificate-oidc-issuer-regexp "https://token.actions.githubusercontent.com" | grep -q "Verification succeeded"; then
          echo ":white_check_mark: SBOM attestation verified" >> $GITHUB_STEP_SUMMARY
          SBOM_VERIFIED=true
        else
          echo ":warning: SBOM attestation verification inconclusive (this is normal for newly built images)" >> $GITHUB_STEP_SUMMARY
        fi

        # Verify Provenance attestation
        echo "### Provenance Attestation (SLSA)" >> $GITHUB_STEP_SUMMARY
        if cosign verify-attestation --type slsaprovenance \
           "$IMAGE_REF" \
           --certificate-identity-regexp "https://github.com/docker/build-push-action" \
           --certificate-oidc-issuer-regexp "https://token.actions.githubusercontent.com" | grep -q "Verification succeeded"; then
          echo ":white_check_mark: Provenance attestation verified with mode=max" >> $GITHUB_STEP_SUMMARY
          echo ":information_source: This means your image includes detailed build information that can be verified." >> $GITHUB_STEP_SUMMARY
          PROVENANCE_VERIFIED=true
        else
          echo ":warning: Provenance attestation verification inconclusive (this is normal for newly built images)" >> $GITHUB_STEP_SUMMARY
        fi

        # Document information about attestations
        cat >> $GITHUB_STEP_SUMMARY << EOF

        ### About Docker Attestations

        **SBOM Attestation**: Software Bill of Materials (SBOM) provides a detailed inventory of components in the container image, helping with security scanning and license compliance.

        **Provenance Attestation**: Documents the build process, including the build platform, source repository, and build parameters, forming a verifiable chain of custody for the container image.

        For more information about Docker build attestations, see [Docker Documentation](https://docs.docker.com/build/ci/github-actions/attestations/).
        EOF

    - name: Set verification results
      id: check_results
      shell: bash
      run: |
        echo "sbom_verified=${{ steps.verify_attestations.outcome == 'success' && contains(steps.verify_attestations.outputs.sbom_verified, 'true') || false }}" >> $GITHUB_OUTPUT
        echo "provenance_verified=${{ steps.verify_attestations.outcome == 'success' && contains(steps.verify_attestations.outputs.provenance_verified, 'true') || false }}" >> $GITHUB_OUTPUT
