name: pre-commit

on:
  schedule:
    # Run nightly at 01:00 UTC (different time than update-versions to avoid overlapping)
    - cron: '0 1 * * *'
  pull_request:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    # Set environment variable to skip hadolint hook
    env:
      SKIP: hadolint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      # Use specialized action for Hadolint
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          ignore: DL3008,DL4001,DL3047,SC2015,SC2016,DL3003

      # Run pre-commit hooks - the SKIP environment variable will make it skip the hadolint hook
      - uses: pre-commit/action@v3.0.1
