name: 'Version Detection'

on:
  workflow_call:
    outputs:
      latest_version:
        description: "Latest stable Zabbix version (highest version number, e.g., 7.2.7 > 7.0.13)"
        value: ${{ jobs.zabbix-version-detection.outputs.latest_version }}
      lts_version:
        description: "LTS Zabbix version (current LTS release from upstream Zabbix)"
        value: ${{ jobs.zabbix-version-detection.outputs.lts_version }}
      all_versions:
        description: "All supported Zabbix versions (comma-separated)"
        value: ${{ jobs.zabbix-version-detection.outputs.all_versions }}
      matrix:
        description: "JSON matrix for building containers"
        value: ${{ jobs.zabbix-version-detection.outputs.matrix }}

jobs:
  zabbix-version-detection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      latest_version: ${{ steps.fetch_zabbix_versions.outputs.latest_version }}
      lts_version: ${{ steps.fetch_zabbix_versions.outputs.lts_version }}
      all_versions: ${{ steps.fetch_zabbix_versions.outputs.all_versions }}
      matrix: ${{ steps.generate_build_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch and save official Zabbix versions
        id: fetch_zabbix_versions
        run: ./scripts/fetch-zabbix-versions.sh

      - name: Generate build matrix for Zabbix versions
        id: generate_build_matrix
        run: ./scripts/generate-build-matrix.sh
        env:
          ALL_VERSIONS: ${{ steps.fetch_zabbix_versions.outputs.all_versions }}
          LTS_VERSION: ${{ steps.fetch_zabbix_versions.outputs.lts_version }}

      # New step to update Dockerfile with the latest version
      - name: Update Dockerfile with latest version
        id: update_dockerfile
        run: ./scripts/update-dockerfile.sh
        env:
          LATEST_VERSION: ${{ steps.fetch_zabbix_versions.outputs.latest_version }}
